name: godot-ci
on:
  push:     
    branches: [ main ]
env:
  EXPORT_NAME: Ashveil
  GODOT_VERSION: 4.4
jobs:
  export-web:
    name: Web Export
    runs-on: windows-latest
    container:
      image: barichello/godot-ci:${GODOT_VERSION}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:     
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |           
          mkdir -v -p build/web
          godot -v --export "Web" ./build/web/index.html
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: web
          path: build/web
      - name: Install rsync 📚         
        run: |           
          apt-get update && apt-get install -y rsync
      - name: Publish to itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: web
          ITCH_GAME: Ashveil
          ITCH_USER: FunB4nan
          PACKAGE: build/web